### ISSUE TITLE
Gradesheet cannot sort by problems

### ISSUE THREAD

**Issue by nayak16** [autolab/Autolab#659] opened 2016-04-22 12:40 UTC
Due to recent changes in the gradesheet page (maybe #643 ) you can no longer sort students based on individual problems in an assessment.

**Comment by zyx-billy** [comment] 2016-04-22 12:54
Yes, this is caused by #643. I've located the problem and will get a fix today.

**Comment by zyx-billy** [comment] 2017-01-18 22:44
fixed with #662 and now merged into master

**Closed by zyx-billy** 2017-01-18 22:44 UTC
