### ISSUE TITLE
Grade All Submissions page should load Autograder output on-demand

### ISSUE THREAD

**Issue by jburns20** [autolab/Autolab#635] opened 2016-02-24 03:18 UTC
Currently, the source of the "Grade All Submissions" page contains the Autograder output for every student's submission, repeated (# of problems) times. This causes the page to load quite slowly, sometimes taking over a minute for large classes or when the autograder feedback is long.

In order to fix this, the autograder output should be removed from the page source, and clicking on a score should cause an AJAX request to retrieve the autograder output.

**Comment by fletcherw** [comment] 2016-02-24 03:22
Just to comment, it's not just that the pages load slowly, it actually causes my web browser to hang (to the point that I'm asked if I want to stop the unresponsive jquery script), making grade all submissions more or less unusable.

**Comment by robsimmons** [comment] 2016-02-24 13:42
@jburns20 is suggesting one particular solution, but the actual issue presenting is that the critical "Grade Submissions" page is unresponsive for 122-sized assignments. (Another solution would be to only load 50 submissions at a time on the grade submission page, another one would be to allow grade submissions to be loaded only for a particular section...)

However, the presenting issue is that 15-122's course staff is having trouble doing its work this semester because the Grade Submissions page hangs. As such, I'm not actually sure if this is an autolab-dev or an autolab-help issue, and if it's the latter that would be useful information.

**Comment by nayak16** [comment] 2016-02-24 17:48
@robsimmons This is an autolab-dev issue since it requires code and architecture changes. However, once a solution is developed, responsibility will be passed to Computing Services to push the change to production this semester. We will get working on this asap.

**Comment by zyx-billy** [comment] 2016-03-03 06:14
Just a quick update

So after changing the page to fetch autograder output on demand, a typical 122 page is reduced from 10+MB to ~1.5MB (which is still pretty big).

But it seems this isn't going to fix the problem. Chrome's timeline shows that in the ~30 seconds it took to load the page, only 15s is spent downloading the huge html. The rest is spent setting up the huge table (with js). Chrome doesn't seem to complain about running a long script, but Firefox would throw an alert, like @fletcherw mentioned.

I'll take a deeper look to see why the current setup is this slow, but I think one simple workaround would be to divide the table into pages (the search would still work globally so there's no hassle in finding someone). Anyone got other suggestions?

**Comment by nayak16** [comment] 2016-03-03 06:35
Have you tried fetching individual student rows on demand? Such as when scrolling, more students are revealed as you go further down. Gmail does this to an extent. Let me know what you find.

**Comment by zyx-billy** [comment] 2016-03-03 07:08
The problem is right now all sorting and searching are done on the client-side (with the datatable plugin), so we have to fetch all rows at once for those functions to work.
I could try making it only draw out the top x number of rows, and render more when the user has scrolled near the bottom.

**Comment by nayak16** [comment] 2016-10-05 21:09
Merged #643

**Closed by nayak16** 2016-10-05 21:09 UTC
Labels: enhancement
