### ISSUE TITLE
Allow students to pick which submission is their final version

### ISSUE THREAD

**Issue by michellexliu** [autolab/Autolab#1722] opened 2023-01-29 19:41 UTC

**Comment by damianhxy** [comment] 2023-01-30 04:23
Duplicate of #940 and #589

**Comment by damianhxy** [comment] 2023-06-04 02:48
Fixed with the addition of the `modifySubmissionScores` hook

(Assuming students want the highest score, this is functionality the instructor should implement. Either by taking max over each problem, or copying the scores over from the best submission)

**Closed by damianhxy** 2023-06-04 02:48 UTC
Labels: Priority: Medium, Type: Enhancement
