### ISSUE TITLE
Tango Error should not cause a 500 Error on Autolab

### ISSUE THREAD

**Issue by 20wildmanj** [autolab/Autolab#1664] opened 2022-12-02 16:31 UTC
**Your environment**
v 2.9.0, most recent commit on master

**Steps To Reproduce**
1. Don't completely set up Tango correctly (for example, forget to start up the docker container)
2. Try submitting an assessment to Autolab for an autograded assignment

**Current behavior**
- Receive a 500 error:
![Screen Shot 2022-12-02 at 11 28 29](https://user-images.githubusercontent.com/25730111/205339908-389a8495-e3b3-4132-86b6-1d92e3d10c1e.png)

**Expected behavior**
- We should return some sort of error flash, as this is not an internal server error but rather an error on Tango's side (which is separate from Autolab)

**Comment by damianhxy** [comment] 2023-06-11 07:10
Unable to reproduce

<img width="1045" alt="Screenshot 2023-06-11 at 15 08 18" src="https://github.com/autolab/Autolab/assets/9074856/de925964-18e3-4565-8664-a69102efcb66">

I'm fairly certain the exception should be caught internally?
<img width="925" alt="Screenshot 2023-06-11 at 15 08 56" src="https://github.com/autolab/Autolab/assets/9074856/31d6e81d-d95a-40fa-abfb-ee6c07a0a46b">

As a side note, `link` under `tango_open` is unused, and the `\n` under `tango_add_job` doesn't work, `<br>` should be used instead.

**Comment by damianhxy** [comment] 2023-06-11 18:32
Closing as can't repro since Joey can't reproduce it either

**Closed by damianhxy** 2023-06-11 18:32 UTC
Labels: Priority: Low, Type: Bug
