### ISSUE TITLE
Default Shibboleth Auth for CMU

### ISSUE THREAD

**Issue by rmzr7** [autolab/Autolab#665] opened 2016-05-11 23:52 UTC
We need an environment variable and have a shibboleth only login for CMU. The current login page is redundant within the CMU context.

**Comment by cg2v** [comment] 2016-06-07 18:17
I was planing on handling that in the webserver. it's as easy as

Redirect /auth/users/sign_in /auth/users/auth/shibboleth

It probably also makes sense to block the other devise endpoints.
adding  only: [:sessions, :omniauth_callbacks] to devise_for in routes.rb takes care of that, but I
don't know how we'd conditionalize that in a way that is useful, so I'd be inclined to maintain it as a local patch.

I also tried removing devise :database_authenticatable from the user model, but that results in a redirect loop

**Comment by nayak16** [comment] 2016-10-05 21:36
@cg2v Any updates on this? We are planning to actually work on fixing this

**Comment by cg2v** [comment] 2016-10-06 20:29
We had the redirect in place for a week or two, but there was at least one student who was unable to log in. I am trying to get more information from them, but they don't seem to have time to test things for me.

I think the student may have somehow not been confirmed, and so shib couldn't log them back in, so the callback redirected them back to the supposed login page, which I redirected back to shib. But I don't know for sure.

**Comment by nayak16** [comment] 2016-10-06 22:03
I see. Do you think it's a good idea in general to have Autolab redirect to the configured auth provider if one exists. Default to the normal login page if one isn't configured.

**Comment by victorhuangwq** [comment] 2020-06-18 13:31
Issue seems to be addressed in the current CMU deployment. Closing

**Closed by victorhuangwq** 2020-06-18 13:31 UTC
Labels: feature
