### ISSUE TITLE
Setting Annotation Score to 0 changes it to None the First Time

### ISSUE THREAD

**Issue by StevenJamesMoore** [autolab/Autolab#896] opened 2017-09-11 20:33 UTC
When creating an annotation, if the score is originally set to '0', it changes to 'None' once it's saved. However, you're then able to edit the annotation and change it from 'None' to '0' and it'll properly save.

In this case, is it desired that a user keep it/change it to 'None' instead of the numerical '0'?

(Reported in ServiceNow under INC0285764)

**Comment by zyx-billy** [comment] 2017-10-11 03:34
Can confirm this is a reproducible issue. It's caused by the string "0" being changed into the number 0 after sending the it to the server and back.

The correct score 0 is stored in the database, so the calculation of scores remains correct. It only shows "None" on the annotations page due to the bug mentioned above (expecting a string "0" but got a number 0).

However, this is still an issue because "None" and "0" are not supposed to be interchangeable semantically. Before a fix is in, though, it doesn't matter if the user changes the score to 0 again, because the next time the annotations page is rendered, it will still show "None".

**Comment by zyx-billy** [comment] 2017-10-29 17:13
Going to redirect this to @TheodorJ for the all new annotations page.

**Comment by victorhuangwq** [comment] 2020-06-18 12:24
Issue not relevant under the new speedgrader annotations page. https://github.com/autolab/Autolab/releases/tag/v2.4.0

**Closed by victorhuangwq** 2020-06-18 12:24 UTC
Labels: annotations, bug
