### ISSUE TITLE
Saving a new user with no fields filled results in 500 error

### ISSUE THREAD

**Issue by 20wildmanj** [autolab/Autolab#1581] opened 2022-08-29 15:30 UTC
Related to #885 

**Your environment**
Both on local dev environment and on nightly servers

**Steps To Reproduce**
1. Go to a course as an instructor and go to "Manage Course"
2. Click on "Manage Students"
3. Click on "Add user to course"
4. Don't fill anything out, scroll to the bottom and click "Save Changes"
5. See resulting error:

On nightly:
![Screen Shot 2022-08-29 at 11 25 00](https://user-images.githubusercontent.com/25730111/187237576-c0ff64bb-e3aa-4aec-be0c-be7c6281672b.png)

On localhost:
![Screen Shot 2022-08-29 at 11 25 47](https://user-images.githubusercontent.com/25730111/187237638-46d65e14-a5d8-4124-af93-b197bc68c9ba.png)

**Current behavior**
We receive an internal error when we try to add an empty user

**Expected behavior**
We should reject the user save without resulting in an internal error

**Comment by damianhxy** [comment] 2022-08-29 17:34
Possible duplicate of #885

**Closed** 2022-09-13 23:04 UTC
Labels: Priority: Low, Type: Bug
