### ISSUE TITLE
Tables Aren't Sortable

### ISSUE THREAD

**Issue by dlbucci** [autolab/Autolab#1] opened 2014-10-27 20:26 UTC
The manage accounts page no longer sorts by column.
I think this has to do with us not including jQuery sorttables in the application layout.  instead, we should include it on any page with a table.

**Comment by Z1MM32M4N** [comment] 2015-01-16 01:04
At least on the Manage Accounts page, it looks like the error was being caused by not calling the `sorttables()` method after the DOM had loaded (or not at all). It's fixed on the Manage Accounts page, and it should be relatively simple to make any other tables sortable by following changes similar to those introduced in #105. 

Since there are tons of tables in the app, it doesn't make economical sense to peck and hunt for all of them. I'll keep this issue open for a while until they gradually are all fixed. When a table is encountered that's not sortable, see #105 for boilerplate code to fix the issue.

**Comment by ymzong** [comment] 2015-01-21 15:57
Fixed by 05d067fdf816aec9f96b574b93e7848d006a0a8a.

**Closed by ymzong** 2015-01-21 15:57 UTC
Labels: bug
