### ISSUE TITLE
Allow users to register themselves for courses using unique links

### ISSUE THREAD

**Issue by nayak16** [autolab/Autolab#764] opened 2017-01-21 18:44 UTC
We should add an extra feature so that an Instructor creating a course can choose whether to allow students to register themselves for the course. This way, we don't need any complicated methods to register contestants for programming challenges; instead, the organization posts a link to the course and the contestants register themselves.

Complement to #420

**Comment by nayak16** [comment] 2017-01-21 21:21
This [link](http://stackoverflow.com/questions/19115929/generating-a-unique-url-with-tokens-in-rails-4-for-an-external-form-response) will be useful

**Comment by damianhxy** [comment] 2023-06-04 02:39
Closing as duplicate of #1786

**Closed** 2023-06-04 02:39 UTC
Labels: Type: Enhancement, Priority: Low
