### ISSUE TITLE
Remove Grading Deadline

### ISSUE THREAD

**Issue by victorhuangwq** [autolab/Autolab#1724] opened 2023-01-29 19:42 UTC
Grading deadline confuses users:
- Users just want to have 1 button to release grades
- Currently instructors have to ensure that the grading deadline is over, before they release grades

**Comment by damianhxy** [comment] 2023-01-30 01:06
Duplicate of #1717

**Comment by damianhxy** [comment] 2023-01-30 20:20
Closed as duplicate

**Closed by damianhxy** 2023-01-30 20:20 UTC
