### ISSUE TITLE
Make "hide comments" button when grading more visible

### ISSUE THREAD

**Issue by jhs-panda** [autolab/Autolab#2221] opened 2024-09-24 01:36 UTC
Requested by 15213.
TA noted that being able to view submissions without grader's added comments would be nice. Mentioned being able to find it occasionally, but not often or easily.
Proposed solution: move button to more visible/accessible location

**Comment by 20wildmanj** [comment] 2024-09-25 03:24
Duplicate of #2203

**Closed by 20wildmanj** 2024-09-25 03:24 UTC
Labels: Priority: Medium, Type: Enhancement
