### ISSUE TITLE
Max Score option - request for a new feature

### ISSUE THREAD

**Issue by rosecatherinek** [autolab/Autolab#940] opened 2017-11-13 19:37 UTC
Hi Team,

I am a TA for a course at CMU that uses Autolab for its assignments. Often, the scores computed on autolab fluctuate because of many reasons. E.g. when we time their code, if the server is loaded, then they get lower scores. E.g. due to random initializations in the code, different runs get higher or lower accuracy scores. 

So, it would be helpful if Autolab had a feature to select the best scores instead of the last scores. Hope you can accommodate this request! Thanks!

**Comment by damianhxy** [comment] 2022-11-24 07:20
Duplicate of #589

**Comment by damianhxy** [comment] 2023-06-04 02:44
Fixed with the addition of the `modifySubmissionScores` hook

**Closed** 2023-06-04 02:45 UTC
Labels: Type: Enhancement, Priority: Low
